from os import PathLike
from typing import AnyStr

def blake2bfile(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def blake2bfilehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def blake2bsum(x: AnyStr | bytearray) -> bytes: ...
def blake2bsumhex(x: AnyStr | bytearray) -> str: ...
def blake2sfile(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def blake2sfilehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def blake2ssum(x: AnyStr | bytearray) -> bytes: ...
def blake2ssumhex(x: AnyStr | bytearray) -> str: ...
def md5file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def md5filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def md5sum(x: AnyStr | bytearray) -> bytes: ...
def md5sumhex(x: AnyStr | bytearray) -> str: ...
def sha1file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha1filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha1sum(x: AnyStr | bytearray) -> bytes: ...
def sha1sumhex(x: AnyStr | bytearray) -> str: ...
def sha224file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha224filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha224sum(x: AnyStr | bytearray) -> bytes: ...
def sha224sumhex(x: AnyStr | bytearray) -> str: ...
def sha256file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha256filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha256sum(x: AnyStr | bytearray) -> bytes: ...
def sha256sumhex(x: AnyStr | bytearray) -> str: ...
def sha384file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha384filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha384sum(x: AnyStr | bytearray) -> bytes: ...
def sha384sumhex(x: AnyStr | bytearray) -> str: ...
def sha3_224file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha3_224filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha3_224sum(x: AnyStr | bytearray) -> bytes: ...
def sha3_224sumhex(x: AnyStr | bytearray) -> str: ...
def sha3_256file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha3_256filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha3_256sum(x: AnyStr | bytearray) -> bytes: ...
def sha3_256sumhex(x: AnyStr | bytearray) -> str: ...
def sha3_384file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha3_384filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha3_384sum(x: AnyStr | bytearray) -> bytes: ...
def sha3_384sumhex(x: AnyStr | bytearray) -> str: ...
def sha3_512file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha3_512filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha3_512sum(x: AnyStr | bytearray) -> bytes: ...
def sha3_512sumhex(x: AnyStr | bytearray) -> str: ...
def sha512file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def sha512filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def sha512sum(x: AnyStr | bytearray) -> bytes: ...
def sha512sumhex(x: AnyStr | bytearray) -> str: ...
def shake_128file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def shake_128filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def shake_128sum(x: AnyStr | bytearray) -> bytes: ...
def shake_128sumhex(x: AnyStr | bytearray) -> str: ...
def shake_256file(path: str | bytes | PathLike[str] | PathLike[bytes]) -> bytes: ...
def shake_256filehex(path: str | bytes | PathLike[str] | PathLike[bytes]) -> str: ...
def shake_256sum(x: AnyStr | bytearray) -> bytes: ...
def shake_256sumhex(x: AnyStr | bytearray) -> str: ...
