from typing import AnyStr, Protocol, TypeVar

_T = TypeVar('_T', AnyStr, bytearray)

def sh_string(s: _T) -> _T: ...
def sh_prepare(variables: dict[AnyStr, AnyStr], export: bool = False) -> str: ...

class _VarArgFormatter(Protocol):
    def __call__(self, *args: AnyStr) -> AnyStr: ...

def sh_command_with(f: str | _VarArgFormatter, *args: AnyStr) -> str: ...
