from typing import AnyStr

from pwnlib.context import LocalContext

@LocalContext
def archname() -> str: ...
@LocalContext
def user_path() -> str | None: ...
@LocalContext
def ld_prefix(
    path: AnyStr | bytearray | None = ..., env: dict[bytes, bytes] | None = ...
) -> str: ...
