from typing import Iterable

def yesno(prompt: str, default: bool | None = ...) -> bool: ...
def options(prompt: str, opts: Iterable[str], default: str | None = ...) -> int: ...
def pause(n: int | None = ...) -> None: ...
def more(text: str) -> None: ...
