update_freq: float
disabled: bool

def available_on_pypi(prerelease: bool = ...) -> bool: ...
def cache_file() -> str | None: ...
def last_check() -> float: ...
def check_automatically() -> None: ...
