class Buffer:
    data: list[bytes]
    size: int
    def __init__(self, buffer_fill_size: int | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __nonzero__(self) -> bool: ...
    def __contains__(self, x: bytes) -> bool: ...
    def index(self, x: bytes) -> int: ...
    def add(self, data: bytes | Buffer) -> None: ...
    def unget(self, data: bytes | Buffer) -> None: ...
    def get(self, want: float = ...) -> bytes: ...
    def get_fill_size(self, size: int | None = ...) -> int: ...
