name: Continuous Integration
on: [push, pull_request]

jobs:

  windows-test:
    runs-on: windows-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    
    - uses: Vampire/setup-wsl@v6
      with:
        distribution: Ubuntu-24.04
        use-cache: 'true'
        additional-packages:
          openssh-server

    - name: Setup Linux SSH server
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -f ~/.ssh/travis -N ''
        echo "TRAVIS_SSH_PUBLIC_KEY=$(cat ~/.ssh/travis.pub)" >> $GITHUB_ENV
        cat >> ~/.ssh/config <<EOF
        Host example.pwnme
            User travis
            HostName 127.0.0.1
            Port 2200
            IdentityFile ~/.ssh/travis
            StrictHostKeyChecking no
        EOF
    
    - name: Setup SSH in WSL2
      shell: wsl-bash {0}
      run: |
        sed -i 's/#Port 22/Port 2200/' /etc/ssh/sshd_config
        service ssh start
        useradd -m travis
        passwd --delete --unlock travis
        chsh --shell /bin/bash travis
        mkdir -p /home/travis/.ssh && chmod 700 /home/travis/.ssh
        echo "${{ env.TRAVIS_SSH_PUBLIC_KEY }}" > /home/travis/.ssh/authorized_keys
        chmod 600 /home/travis/.ssh/authorized_keys

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade --editable .

    - name: Install documentation dependencies
      run: pip install -r docs/requirements.txt

    - name: Sanity checks
      run: |
        ssh -v travis@example.pwnme id
        python -bb -c 'from pwn import *'
        python -bb examples/text.py

    - name: Coverage doctests
      run: |
        python -bb -m coverage run -m sphinx -b doctest docs/source docs/build/doctest

