name: Continuous Integration
on: [push, pull_request]

jobs:

  windows-test:
    runs-on: windows-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    
    - name: Setup Linux SSH server
      shell: bash
      run: |
        docker run --name sshd-linux --rm --entrypoint "/usr/bin/sleep" --detach --publish 2200:22 ubuntu:latest infinity
        docker exec sshd-linux bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -f ~/.ssh/travis -N ''
        docker exec --user root sshd-linux bash -c "useradd -m travis && passwd --delete --unlock travis && chsh --shell /bin/bash travis"
        docker exec --user travis sshd-linux bash -c "mkdir -p /home/travis/.ssh && chmod 700 /home/travis/.ssh"
        docker cp ~/.ssh/travis.pub sshd-linux:/home/travis/.ssh/authorized_keys
        cat >> ~/.ssh/config <<EOF
        Host example.pwnme
            User travis
            HostName 127.0.0.1
            Port 2200
            IdentityFile ~/.ssh/travis
            StrictHostKeyChecking no
        EOF
        ssh -v travis@example.pwnme id

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade --editable .

    - name: Install documentation dependencies
      run: pip install -r docs/requirements.txt

    - name: Sanity checks
      run: |
        python -bb -c 'from pwn import *'
        python -bb examples/text.py

    - name: Coverage doctests
      run: |
        python -bb -m coverage run -m sphinx -b doctest docs/source docs/build/doctest

